// This file is auto-generated by @hey-api/openapi-ts

export type AppointmentItem = {
  Id?: string;
  MaHen?: string;
  BenhNhanId?: string;
  NgayHen?: string;
  NgayHenTo?: string;
  GioHen?: number;
  NgayTao?: string;
  TrangThai?: string;
  TagId?: string | null;
  ColorCode?: string | null;
  GoogleColorId?: string | null;
  Ma?: string | null;
  HoTen?: string;
  DienThoai?: string;
  TenBacSi?: string;
  GoogleCalendarId?: string | null;
  ProviderId?: string;
  ServiceId?: string;
  NoiDungHen?: string;
  CCCD?: string;
  DOB?: string;
  Sex?: number;
  IdInPKV?: string | null;
  PhongKham?: string;
  IsOnline?: boolean;
};

export type BookingServiceItem = {
  Id?: string;
  Domain?: string;
  Code?: string;
  CodeLink?: string | null;
  Name?: string;
  Description?: string;
  Image?: string | null;
  Price?: number | null;
  Index?: number;
  Providers?: Array<Provider>;
  HidePriceOnBookingPage?: boolean;
  DisplayOnBookingPage?: boolean;
  DurationTime?: number;
  HideDurationTimeOnBookingPage?: boolean;
  ProviderStr?: string;
  IsSpecial?: boolean;
  Active?: boolean;
};

export type DoctorItem = {
  Domain?: string;
  Title?: string;
  PreviewContent?: string;
  Content?: string;
  ImageUrl?: string;
  KhoaDieuTri?: string;
  NangLuc?: string;
  Note?: string;
  UuTien?: number;
  Active?: boolean;
  Id?: string;
};

export type DoctorPagingResponse = {
  Value?: Array<DoctorItem>;
  Total?: number;
  Sum?: number;
};

export type News = {
  /**
   * Trạng thái hoạt động
   */
  Active?: boolean;
  /**
   * Nội dung bài viết (có thể là null)
   */
  Content?: string | null;
  /**
   * Ngày tạo (ISO)
   */
  CreateDate?: string;
  /**
   * Ngày hiển thị (có thể là null)
   */
  DisplayDate?: string | null;
  /**
   * Hiển thị trong banner
   */
  DisplayInBanner?: boolean;
  /**
   * Hiển thị trong Zalo OA
   */
  DisplayInZaloOA?: boolean;
  /**
   * Tên miền
   */
  Domain?: string;
  /**
   * URL bên ngoài (có thể null)
   */
  ExternalUrl?: string | null;
  /**
   * ID bài viết
   */
  Id?: string;
  /**
   * ID danh mục tin tức
   */
  NewsCategoryId?: string | null;
  /**
   * Loại tin tức
   */
  NewsType?: string | null;
  /**
   * Nội dung xem trước
   */
  PreviewContent?: string;
  /**
   * ID nhà cung cấp
   */
  ProviderId?: string | null;
  /**
   * Ngày xuất bản
   */
  PublishDate?: string;
  /**
   * Trạng thái xuất bản
   */
  PublishState?: boolean;
  /**
   * ID dịch vụ
   */
  ServiceId?: string | null;
  /**
   * Tiêu đề bài viết
   */
  Title?: string;
  /**
   * Ngày cập nhật
   */
  UpdateDate?: string;
  /**
   * URL bài viết
   */
  Url?: string;
};

export type NewsCategory = {
  /**
   * ID danh mục tin tức
   */
  NewsCategoryId?: string | null;
  /**
   * Danh sách bài viết thuộc danh mục
   */
  NewsList?: Array<News>;
};

export type NewsCategoryItem = {
  Title?: string;
  Url?: string;
  Id?: string;
};

export type Provider = {
  Id?: string;
  Domain?: string;
  Code?: string | null;
  CodeLink?: string | null;
  Name?: string;
  Description?: string;
  UpdateDate?: string;
  Mobile?: string | null;
  Email?: string | null;
  Facebook?: string | null;
  FacebookPost?: string | null;
  Image?: string | null;
  DisplayOnBookingPage?: boolean;
  Index?: number;
  CategoryId?: string | null;
  AccountId?: string | null;
  NumberForWarning?: number | null;
  Active?: boolean;
};

export type ProviderBrief = {
  Id?: string;
  Code?: string | null;
  Name?: string;
  Description?: string;
  Image?: string | null;
  Index?: number;
  BookingCount?: number;
  NumberForWarning?: number | null;
};

export type ProviderListResponse = {
  Value?: Array<ProviderBrief>;
  Total?: number;
  Sum?: number;
};

export type ScheduleDto = {
  Id?: string;
  Domain?: string;
  ScheduleDate?: string;
  FromTime?: number;
  ToTime?: number;
  Visible?: boolean;
  ServeCount?: number;
  BookingCount?: number;
  QueueCount?: number;
  ProviderId?: string;
  ServiceId?: string | null;
  OperatingStatus?: number;
};

export type ScheduleListResponse = Array<ScheduleDto>;

export type ServiceItem = {
  Domain?: string;
  Name?: string;
  LongDescription?: string;
  ShortDescription?: string;
  ImageUrl?: string;
  Level?: number;
  ParentService?: {
    [key: string]: unknown;
  } | null;
  ParentId?: string | null;
  Price?: number;
  Price_2?: number;
  PriceStr?: string | null;
  UuTien?: number;
  Active?: boolean;
  Id?: string;
};

export type ServiceListResponse = Array<BookingServiceItem>;

export type ServicePagingResponse = {
  Value?: Array<ServiceItem>;
  Total?: number;
  Sum?: number;
};

export type ZaloAuthResponse = {
  code?: string | null;
  success?: boolean;
  message?: string | null;
  result?: ZaloUserResponse;
};

export type ZaloUserRequest = {
  id?: string;
  name?: string;
  avatar?: string;
  followedOA?: boolean;
  isSensitive?: boolean;
};

export type ZaloUserResponse = {
  Mobile?: string;
  Ten?: string;
  DOB?: string;
  Sex?: number;
  ImageUrl?: string | null;
  Email?: string | null;
  PatientCode?: string | null;
  FirebaseId?: string | null;
  JwtToken?: string;
  LoginCount?: number;
  RefreshToken?: string;
  CCCD?: string;
  BHYT?: string | null;
  ProvinceId?: string;
  DistrictId?: string;
  WardsId?: string;
  Address?: string;
  Domain?: string | null;
  PatientId?: string | null;
  CreateDate?: string;
  UpdateDate?: string;
  Active?: boolean;

  Id?: string;
};

export type GetByDomainBookieServiceData = {
  /**
   * Tên miền hệ thống (ví dụ: demo)
   */
  domain: string;
};

export type GetByDomainBookieServiceResponse = Array<ServiceItem>;

export type GetByDomainBookieProviderData = {
  /**
   * Tên miền hệ thống
   */
  domain: string;
  /**
   * Danh sách providerId (ngăn cách bằng dấu phẩy)
   */
  strProviderId: string;
  /**
   * Hiển thị chi tiết
   */
  viewDetail?: boolean;
};

export type GetByDomainBookieProviderResponse = ProviderListResponse;

export type GetByDomainScheduleData = {
  /**
   * Ngày lấy lịch (yyyy-MM-dd)
   */
  date: string;
  /**
   * Tên miền hệ thống
   */
  domain: string;
  /**
   * ID nhà cung cấp
   */
  idProvider: string;
  /**
   * ID dịch vụ (có thể để trống)
   */
  idService?: string;
};

export type GetByDomainScheduleResponse = ScheduleListResponse;

export type GetByDomainCmsDichVuPagingData = {
  /**
   * Tên miền hệ thống
   */
  domain: string;
  /**
   * Trang hiện tại
   */
  page: number;
  /**
   * Từ khóa tìm kiếm
   */
  search?: string;
  /**
   * Số lượng item mỗi trang
   */
  size: number;
};

export type GetByDomainCmsDichVuPagingResponse = ServicePagingResponse;

export type GetByDomainNewsNewsGroupedByCategoryData = {
  category?: string;
  domain: string;
  page?: number;
  pageSize?: number;
};

export type GetByDomainNewsNewsGroupedByCategoryResponse = {
  Value?: Array<NewsCategory>;
  Total?: number;
  Sum?: number;
};

export type GetByDomainNewsCategoryData = {
  domain: string;
  page?: number;
  size?: number;
};

export type GetByDomainNewsCategoryResponse = {
  Value?: Array<NewsCategoryItem>;
  Total?: number;
  Sum?: number;
};

export type GetByDomainBookieAppointmentPhantrangData = {
  _from?: string;
  date?: string;
  domain: string;
  existMobile?: number;
  filterDate?: string;
  page?: number;
  pageSize?: number;
  providerId?: string;
  search?: string;
  to?: string;
  trangThai?: string;
  typeOfAppointment?: number;
};

export type GetByDomainBookieAppointmentPhantrangResponse = {
  Value?: Array<AppointmentItem>;
  Total?: number;
  Sum?: number;
};

export type GetByDomainBookieBannersData = {
  /**
   * Domain hệ thống
   */
  domain: string;
  /**
   * Trang hiện tại
   */
  page?: number;
  /**
   * Số lượng item trên mỗi trang
   */
  pageSize?: number;
};

export type GetByDomainBookieBannersResponse = {
  Value?: Array<{
    Id?: string;
    Title?: string;
    PreviewContent?: string;
    Url?: string;
  }>;
  Total?: number;
  Sum?: number;
};

export type GetByDomainCmsdoctorPagingData = {
  /**
   * Tên miền hệ thống
   */
  domain: string;
  /**
   * Trang hiện tại
   */
  page: number;
  /**
   * Từ khóa tìm kiếm (tùy chọn)
   */
  search?: string;
  /**
   * Số lượng item mỗi trang
   */
  size: number;
};

export type GetByDomainCmsdoctorPagingResponse = DoctorPagingResponse;

export type PostByDomainBookieZaloInfoData = {
  domain: string;
  requestBody: ZaloUserRequest;
  token: string;
  zaloCode: string;
};

export type PostByDomainBookieZaloInfoResponse = ZaloAuthResponse;
